"""empty message

Revision ID: 400754f065c4
Revises: 194ffe48fcb6
Create Date: 2023-08-10 09:54:02.641620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '400754f065c4'
down_revision = '194ffe48fcb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
